services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  api:
    build: .
    environment:
      DATABASE_CONNECTION: postgresql://postgres:postgres123@db:5432/postgres
    depends_on:
        db: 
          condition: service_healthy
    ports:
      - "8000:8000"
    command:
      sh -c "alembic upgrade head && uvicorn hello:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata: