"""empty message

Revision ID: 2c46790e5189
Revises: 
Create Date: 2026-06-22 22:04:54.985332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c46790e5189'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_mood',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('happiness', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('stressed', sa.Boolean(), nullable=False),
    sa.Column('friends_family_time', sa.Boolean(), nullable=False),
    sa.Column('weather_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_mood')
    # ### end Alembic commands ###
