"""add daily_automated_data table

Revision ID: 40287118d1be
Revises: 2c46790e5189
Create Date: 2026-06-30 21:58:41.949120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40287118d1be'
down_revision: Union[str, Sequence[str], None] = '2c46790e5189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_automated_data',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weather_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.drop_column('daily_mood', 'weather_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_mood', sa.Column('weather_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('daily_automated_data')
    # ### end Alembic commands ###
