"""create daily_mood table

Revision ID: d545e86b47b8
Revises: 
Create Date: 2026-06-02 22:14:42.284862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd545e86b47b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_mood',
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('Happiness', sa.Integer(), nullable=False),
    sa.Column('Energy', sa.Integer(), nullable=False),
    sa.Column('Stressed', sa.Boolean(), nullable=False),
    sa.Column('FriendsFamilyTime', sa.Boolean(), nullable=False),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_mood')
    # ### end Alembic commands ###
